"""Tables and named numbers for the research paper, written as LaTeX. Presentation only.

Every function takes values computed elsewhere and returns text. The paper's
tables are generated rather than typed, so a number cannot drift between the
record it comes from and the page that prints it.
"""

from __future__ import annotations

import math
import re
from collections.abc import Mapping, Sequence

LATEX_SPECIAL_CHARACTERS: dict[str, str] = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}

MACRO_NAME = re.compile(r"^[A-Za-z]+$")
"""LaTeX control words are letters only; a digit or underscore would end the name early."""


class LatexError(ValueError):
    """A table or macro could not be written as valid LaTeX."""


def escape(text: str) -> str:
    """Make plain text safe to place in a LaTeX document."""
    return "".join(LATEX_SPECIAL_CHARACTERS.get(character, character) for character in text)


def signed(value: float, digits: int) -> str:
    """A number with an explicit sign and a true minus, in math mode.

    Skill scores and differences have a meaningful zero, so the sign is always
    printed: +0.240 and -0.056 read as a pair, 0.240 and -0.056 do not.
    """
    if not math.isfinite(value):
        return "--"
    rounded = round(value, digits)
    if rounded == 0.0:
        rounded = 0.0
    return f"${rounded:+.{digits}f}$"


def unsigned(value: float, digits: int) -> str:
    """A number without a forced sign, for quantities that are never negative."""
    if not math.isfinite(value):
        return "--"
    return f"{value:.{digits}f}"


def interval(lower: float, upper: float, digits: int) -> str:
    """A confidence interval as [lower, upper], both signed."""
    return f"[{signed(lower, digits)}, {signed(upper, digits)}]"


def tabular(
    headings: Sequence[str],
    rows: Sequence[Sequence[str]],
    column_format: str,
    *,
    long: bool = False,
    caption: str | None = None,
    label: str | None = None,
) -> str:
    """A booktabs table body. Cells are written as given, so escape plain text first.

    ``long`` writes a ``longtable`` that breaks across pages, for the appendix
    tables that run to a hundred rows or more; it carries its caption and label
    itself, and repeats its headings on every page. A short table is a bare
    ``tabular`` that the paper wraps in its own ``table`` float.
    """
    width = len(headings)
    for position, row in enumerate(rows):
        if len(row) != width:
            raise LatexError(
                f"row {position} has {len(row)} cells but the table has {width} headings. "
                "Build every row from the same column list."
            )
    heading_line = " & ".join(headings) + r" \\"
    body = [" & ".join(row) + r" \\" for row in rows]
    if not long:
        return "\n".join(
            [
                rf"\begin{{tabular}}{{{column_format}}}",
                r"\toprule",
                heading_line,
                r"\midrule",
                *body,
                r"\bottomrule",
                r"\end{tabular}",
                "",
            ]
        )
    if caption is None or label is None:
        raise LatexError("a long table carries its own caption and label; pass both")
    return "\n".join(
        [
            rf"\begin{{longtable}}{{{column_format}}}",
            rf"\caption{{{caption}}}\label{{{label}}}\\",
            r"\toprule",
            heading_line,
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            heading_line,
            r"\midrule",
            r"\endhead",
            r"\midrule",
            rf"\multicolumn{{{width}}}{{r}}{{\footnotesize continued on the next page}}\\",
            r"\endfoot",
            r"\bottomrule",
            r"\endlastfoot",
            *body,
            r"\end{longtable}",
            "",
        ]
    )


def macros(numbers: Mapping[str, str]) -> str:
    """One ``\\newcommand`` per named number, sorted so the file is stable.

    The paper refers to a generated number by name, never by value, so changing
    the record changes the page.
    """
    lines = ["% Generated by `forecast paper-assets`. Do not edit by hand.", ""]
    for name in sorted(numbers):
        if not MACRO_NAME.match(name):
            raise LatexError(
                f"{name!r} is not a usable LaTeX macro name: use letters only, "
                "for example BlendSkillOneYear"
            )
        lines.append(rf"\newcommand{{\{name}}}{{{numbers[name]}}}")
    lines.append("")
    return "\n".join(lines)
